language: cpp
jobs:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libcurl4-openssl-dev

    - os: osx
      osx_image: xcode12.5

    - os: freebsd
      addons:
        pkg:
          - cmake
          - curl

    - os: windows

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$TRAVIS_OS_NAME" == "osx"     ]; then brew update; brew unlink cmake; brew install cmake curl; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install -y make curl  ; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then 
      mkdir c:\library
      cd c:\library
      wget --no-check-certificate "https://curl.haxx.se/download/curl-7.48.0.zip"
      7z x curl-7.48.0.zip -o curl
      cd curl
      cmake .
      cmake --build .
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cmake -S . -B build
      cmake --build build
    else
      cmake .
      make -j 4
    fi