language: cpp
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libcurl4-openssl-dev

    - os: osx
      osx_image: xcode12.5

    - os: freebsd
      addons:
        pkg:
          - cmake
          - curl
        env:
          - IGNORE_OSVERSION=yes

    - os: windows

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$TRAVIS_OS_NAME" == "osx"     ]; then brew update; brew unlink cmake; brew install cmake curl; fi

script:
  - cmake .
  - make -j 4