language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  - freebsd

osx_image: xcode12.5

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$TRAVIS_OS_NAME" == "osx"     ]; then brew update; brew unlink cmake; brew install cmake curl; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"   ]; then sudo apt-get update; sudo apt-get -y install cmake libcurl4-openssl-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "freebsd" ]; then sudo pkg update; sudo pkg install cmake curl; fi

script:
  - cmake .
  - make -j 4