shallow_clone: true
clone_folder: c:\projects\libssllabs

environment:
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"

branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  # needed to download other deps
  - cinst wget git

  # install curl
  - cmd: mkdir c:\library
  - cmd: cd c:\library
  - cmd: wget "https://curl.haxx.se/download/curl-7.48.0.zip"
  - cmd: 7z x curl-7.48.0.zip
  - cmd: ren curl-7.48.0 curl
  - cmd: cd curl
  - cmd: cmake .
  - cmd: cmake --build .

  - ps: cd "c:\projects\libssllabs"
  - cmd: git submodule init
  - cmd: git submodule update

build_script:
  - ps: cd "c:\projects\libssllabs"
  - cmd: cmake .
  - cmd: cmake --build .
