version: 2.1
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt update && apt install cmake libcurl4-openssl-dev -y
      - run: mkdir -p build && cd build
      - run: cmake ..
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
